// app/(public)/vehicles/_actions/car-database.ts
// Normalized car database for the new client
import { Car } from "@/types/car";

export const carsDatabase: Car[] = [
  // Mercedes-Benz G 63 AMG
  {
    id: "mercedes-amg-g63",
    name: "Mercedes-AMG G 63",
    image: "/images-from-cms/50408_st0640_119.png",
    images: ["/images-from-cms/50408_st0640_119.png"],
    rating: 4.8,
    reviews: 142,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: 1800,
    category: "luxury",
    brand: "mercedes",
    description:
      "The Mercedes-AMG G 63 is an iconic luxury SUV that combines rugged off-road capability with exceptional performance and prestige. This legendary G-Class offers a handcrafted AMG engine, sophisticated luxury, and unmistakable design that makes a powerful statement wherever you go.",
    specs: {
      engine: "4.0L V8 Biturbo",
      power: "577 hp",
      torque: "850 Nm",
      acceleration: "4.5 sec (0-100 km/h)",
      topSpeed: "220 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "13.1 L/100km",
      driveTrain: "AWD",
      features: [
        "AMG DYNAMIC SELECT",
        "Burmester surround sound system",
        "Adaptive suspension",
        "Nappa leather upholstery",
        "AMG performance exhaust",
        "MBUX infotainment system",
        "Heated and ventilated seats",
        "360° camera",
      ],
    },
  },

  // BMW X6
  {
    id: "bmw-x6",
    name: "BMW X6",
    image: "/images-from-cms/bmw-x6-01-2048x2048.jpg",
    images: ["/images-from-cms/bmw-x6-01-2048x2048.jpg"],
    rating: 4.6,
    reviews: 98,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: 800,
    category: "luxury",
    brand: "bmw",
    description:
      "The BMW X6 combines the commanding presence of an SUV with the dynamic styling of a coupe. This Sports Activity Coupe delivers exceptional performance, cutting-edge technology, and luxurious comfort in a distinctive package that stands out from the crowd.",
    specs: {
      engine: "3.0L TwinPower Turbo Inline-6",
      power: "335 hp",
      torque: "450 Nm",
      acceleration: "5.5 sec (0-100 km/h)",
      topSpeed: "250 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "8.5 L/100km",
      driveTrain: "AWD",
      features: [
        "BMW Live Cockpit Professional",
        "Panoramic glass roof",
        "Vernasca leather upholstery",
        "Harman Kardon surround sound",
        "Adaptive LED headlights",
        "Parking Assistant Plus",
        "Driving Assistant Professional",
        "Wireless charging",
      ],
    },
  },

  // GMC Yukon
  {
    id: "gmc-yukon",
    name: "GMC Yukon",
    image: "/images-from-cms/g2.jpg",
    images: ["/images-from-cms/g2.jpg"],
    rating: 4.5,
    reviews: 87,
    passengers: 8,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: 600,
    category: "economy", // Family category mapped to Economy
    brand: "gmc",
    description:
      "The GMC Yukon is a full-size SUV that offers exceptional space, capability, and comfort for families. With its powerful engine options, advanced technology, and premium interior, it provides a commanding presence on the road while ensuring everyone travels in comfort.",
    specs: {
      engine: "5.3L V8",
      power: "355 hp",
      torque: "519 Nm",
      acceleration: "6.8 sec (0-100 km/h)",
      topSpeed: "180 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "12.4 L/100km",
      driveTrain: "RWD",
      features: [
        "GMC Infotainment System",
        "Tri-zone automatic climate control",
        "Power-folding third-row seats",
        "Bose premium audio system",
        "Advanced trailering system",
        "Rear vision camera",
        "Heated front seats",
        "Remote vehicle start",
      ],
    },
  },

  // Mercedes-Benz C200
  {
    id: "mercedes-c200",
    name: "Mercedes-Benz C200",
    image: "/images-from-cms/2023-mercedes-benz-c-class-2.png",
    images: ["/images-from-cms/2023-mercedes-benz-c-class-2.png"],
    rating: 4.6,
    reviews: 124,
    passengers: 5,
    airConditioning: true,
    doors: 4,
    transmission: "Auto",
    price: 600,
    category: "luxury",
    brand: "mercedes",
    description:
      "The Mercedes-Benz C200 combines elegant design with advanced technology and efficient performance. This compact luxury sedan offers a refined driving experience with its sophisticated interior, intuitive MBUX infotainment system, and comprehensive safety features.",
    specs: {
      engine: "1.5L Turbocharged Inline-4 with EQ Boost",
      power: "204 hp",
      torque: "300 Nm",
      acceleration: "7.3 sec (0-100 km/h)",
      topSpeed: "250 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "6.8 L/100km",
      driveTrain: "RWD",
      features: [
        "MBUX infotainment system",
        "64-color ambient lighting",
        "Artico upholstery",
        "Wireless smartphone integration",
        "Active Brake Assist",
        "Parking package with 360° camera",
        "Keyless-Go",
        "Panoramic sliding sunroof",
      ],
    },
  },

  // Audi A3
  {
    id: "audi-a3",
    name: "Audi A3",
    image: "/images-from-cms/cc_2024AUC150003_01_640_2Y2Y.png",
    images: ["/images-from-cms/cc_2024AUC150003_01_640_2Y2Y.png"],
    rating: 4.5,
    reviews: 156,
    passengers: 5,
    airConditioning: true,
    doors: 4,
    transmission: "Auto",
    price: 350,
    category: "luxury",
    brand: "audi",
    description:
      "The Audi A3 delivers premium compact luxury with its sophisticated design, advanced technology, and dynamic performance. This elegant sedan combines Audi's renowned build quality with modern features and efficient powertrains for an exceptional driving experience.",
    specs: {
      engine: "2.0L TFSI Turbocharged Inline-4",
      power: "190 hp",
      torque: "320 Nm",
      acceleration: "7.0 sec (0-100 km/h)",
      topSpeed: "250 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "6.3 L/100km",
      driveTrain: "FWD",
      features: [
        "Audi Virtual Cockpit",
        "MMI touch display",
        "Audi smartphone interface",
        "LED headlights",
        "Parking system plus",
        "Audi pre sense front",
        "Alcantara/leather combination",
        "Panoramic sunroof",
      ],
    },
  },

  // Audi A6
  {
    id: "audi-a6",
    name: "Audi A6",
    image: "/images-from-cms/Audi-A6.webp",
    images: ["/images-from-cms/Audi-A6.webp"],
    rating: 4.7,
    reviews: 203,
    passengers: 5,
    airConditioning: true,
    doors: 4,
    transmission: "Auto",
    price: 700,
    category: "luxury",
    brand: "audi",
    description:
      "The Audi A6 represents executive luxury at its finest, combining elegant design with cutting-edge technology and exceptional performance. This sophisticated sedan offers a spacious, premium interior, advanced driver assistance systems, and powerful engine options.",
    specs: {
      engine: "2.0L TFSI Turbocharged Inline-4",
      power: "245 hp",
      torque: "370 Nm",
      acceleration: "6.8 sec (0-100 km/h)",
      topSpeed: "250 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "7.1 L/100km",
      driveTrain: "FWD",
      features: [
        "Audi Virtual Cockpit plus",
        "MMI touch response",
        "Matrix LED headlights",
        "Bang & Olufsen sound system",
        "Audi pre sense city",
        "360° camera system",
        "Valcona leather upholstery",
        "Adaptive cruise control",
      ],
    },
  },

  // Lamborghini Urus
  {
    id: "lamborghini-urus",
    name: "Lamborghini Urus",
    image: "/images-from-cms/Lamborghini-Urus.jpg",
    images: ["/images-from-cms/Lamborghini-Urus.jpg"],
    rating: 4.9,
    reviews: 89,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: 2800,
    category: "luxury",
    brand: "lamborghini",
    description:
      "The Lamborghini Urus is the world's first Super Sport Utility Vehicle, combining the soul of a super sports car with the functionality of an SUV. With its powerful engine, exceptional performance, and unmistakable Lamborghini design, it delivers an unparalleled driving experience.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      power: "650 hp",
      torque: "850 Nm",
      acceleration: "3.6 sec (0-100 km/h)",
      topSpeed: "305 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "12.7 L/100km",
      driveTrain: "AWD",
      features: [
        "Lamborghini Infotainment System III",
        "Tamburo driving mode selector",
        "ANIMA (Adaptive Network Intelligent Management)",
        "Adaptive air suspension",
        "Carbon ceramic brakes",
        "Bang & Olufsen sound system",
        "Alcantara and leather interior",
        "21-inch alloy wheels",
      ],
    },
  },

  // Porsche 911 Carrera
  {
    id: "porsche-911-carrera",
    name: "Porsche 911 Carrera",
    image: "/images-from-cms/Porsche-carrera.jpeg",
    images: ["/images-from-cms/Porsche-carrera.jpeg"],
    rating: 4.9,
    reviews: 167,
    passengers: 4,
    airConditioning: true,
    doors: 2,
    transmission: "Auto",
    price: 2000,
    category: "luxury",
    brand: "porsche",
    description:
      "The Porsche 911 Carrera is an icon of sports car excellence, combining legendary performance with everyday usability. With its rear-engine layout, precise handling, and powerful flat-six engine, it delivers an exhilarating driving experience that has defined sports car performance for generations.",
    specs: {
      engine: "3.0L Twin-Turbo Flat-6",
      power: "385 hp",
      torque: "450 Nm",
      acceleration: "4.2 sec (0-100 km/h)",
      topSpeed: "293 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "9.4 L/100km",
      driveTrain: "RWD",
      features: [
        "Porsche Communication Management",
        "Sport Chrono Package",
        "PASM (Porsche Active Suspension Management)",
        "Sport exhaust system",
        "Bose sound system",
        "Leather interior",
        "20-inch Carrera S wheels",
        "PDK transmission",
      ],
    },
  },

  // Porsche Cayenne
  {
    id: "porsche-cayenne",
    name: "Porsche Cayenne",
    image: "/images-from-cms/Porsche-cayenne.jpg",
    images: ["/images-from-cms/Porsche-cayenne.jpg"],
    rating: 4.7,
    reviews: 145,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: 1200,
    category: "luxury",
    brand: "porsche",
    description:
      "The Porsche Cayenne combines the performance of a sports car with the versatility of an SUV. This powerful luxury SUV delivers exceptional driving dynamics, advanced technology, and premium comfort, making it the perfect vehicle for both daily driving and adventurous journeys.",
    specs: {
      engine: "3.0L Turbocharged V6",
      power: "340 hp",
      torque: "450 Nm",
      acceleration: "6.2 sec (0-100 km/h)",
      topSpeed: "245 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "9.2 L/100km",
      driveTrain: "AWD",
      features: [
        "Porsche Communication Management",
        "PASM (Porsche Active Suspension Management)",
        "Panoramic roof system",
        "Bose sound system",
        "Adaptive air suspension",
        "Sport Chrono Package",
        "Leather interior",
        "21-inch alloy wheels",
      ],
    },
  },

  // Porsche Macan
  {
    id: "porsche-macan",
    name: "Porsche Macan",
    image: "/images-from-cms/Porsche-macan.jpeg",
    images: ["/images-from-cms/Porsche-macan.jpeg"],
    rating: 4.6,
    reviews: 132,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: 900,
    category: "luxury",
    brand: "porsche",
    description:
      "The Porsche Macan is a compact luxury SUV that delivers sports car performance in a practical package. With its agile handling, powerful engines, and premium interior, it offers the perfect blend of everyday usability and dynamic driving pleasure.",
    specs: {
      engine: "2.0L Turbocharged Inline-4",
      power: "265 hp",
      torque: "400 Nm",
      acceleration: "6.7 sec (0-100 km/h)",
      topSpeed: "227 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "8.9 L/100km",
      driveTrain: "AWD",
      features: [
        "Porsche Communication Management",
        "PASM (Porsche Active Suspension Management)",
        "Panoramic roof system",
        "Bose sound system",
        "Adaptive air suspension",
        "Sport Chrono Package",
        "Leather interior",
        "20-inch alloy wheels",
      ],
    },
  },

  // Range Rover Vogue
  {
    id: "range-rover-vogue",
    name: "Range Rover Vogue",
    image:
      "/images-from-cms/range-rover-vogue-1-e1683093029567-1024x768-1-e1712044970114-768x658.png",
    images: [
      "/images-from-cms/range-rover-vogue-1-e1683093029567-1024x768-1-e1712044970114-768x658.png",
    ],
    rating: 4.8,
    reviews: 178,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: 1600,
    category: "luxury",
    brand: "range-rover",
    description:
      "The Range Rover Vogue represents the pinnacle of luxury SUVs, combining exceptional refinement with legendary off-road capability. With its sophisticated design, sumptuous interior, and advanced technology, it delivers an unparalleled premium experience.",
    specs: {
      engine: "3.0L Inline-6 Turbocharged",
      power: "400 hp",
      torque: "550 Nm",
      acceleration: "6.1 sec (0-100 km/h)",
      topSpeed: "225 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "9.1 L/100km",
      driveTrain: "AWD",
      features: [
        "Touch Pro Duo infotainment",
        "Meridian sound system",
        "Adaptive Dynamics",
        "Terrain Response 2",
        "Panoramic roof",
        "Windsor leather upholstery",
        "Rear seat entertainment",
        "360° camera system",
      ],
    },
  },

  // Range Rover Sport
  {
    id: "range-rover-sport",
    name: "Range Rover Sport",
    image: "/images-from-cms/Range-Rover-sport.jpg",
    images: ["/images-from-cms/Range-Rover-sport.jpg"],
    rating: 4.7,
    reviews: 156,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: 1500,
    category: "luxury",
    brand: "range-rover",
    description:
      "The Range Rover Sport combines dynamic performance with luxury and capability. This athletic SUV delivers exhilarating on-road performance while maintaining the legendary off-road prowess that Range Rover is known for, all wrapped in a sophisticated and modern design.",
    specs: {
      engine: "3.0L Inline-6 Turbocharged",
      power: "400 hp",
      torque: "550 Nm",
      acceleration: "5.9 sec (0-100 km/h)",
      topSpeed: "225 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "9.3 L/100km",
      driveTrain: "AWD",
      features: [
        "Touch Pro Duo infotainment",
        "Meridian sound system",
        "Adaptive Dynamics",
        "Terrain Response 2",
        "Panoramic roof",
        "Windsor leather upholstery",
        "Dynamic Response Pro",
        "360° camera system",
      ],
    },
  },

  // Bentley Bentayga
  {
    id: "bentley-bentayga",
    name: "Bentley Bentayga",
    image: "/images-from-cms/bentley_bentayga_luxury_suv_01_277f358d6d.png",
    images: ["/images-from-cms/bentley_bentayga_luxury_suv_01_277f358d6d.png"],
    rating: 4.9,
    reviews: 94,
    passengers: 5,
    airConditioning: true,
    doors: 5,
    transmission: "Auto",
    price: 3000,
    category: "luxury",
    brand: "bentley",
    description:
      "The Bentley Bentayga is the world's most luxurious SUV, combining exceptional performance with unparalleled craftsmanship and refinement. This handcrafted masterpiece delivers extraordinary power, sophisticated technology, and bespoke luxury that defines the Bentley experience.",
    specs: {
      engine: "4.0L Twin-Turbo V8",
      power: "550 hp",
      torque: "770 Nm",
      acceleration: "4.5 sec (0-100 km/h)",
      topSpeed: "290 km/h",
      fuelType: "Gasoline",
      fuelConsumption: "11.4 L/100km",
      driveTrain: "AWD",
      features: [
        "Bentley Rotating Display",
        "Naim for Bentley sound system",
        "Bentley Dynamic Ride",
        "All-Terrain Specification",
        "Panoramic glass roof",
        "Mulliner Driving Specification",
        "Handcrafted leather interior",
        "22-inch alloy wheels",
      ],
    },
  },
];
